// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlDV8cFGhp1NPohbdDY-ZgC4OxPwQ6rVQ',
    appId: '1:205307768003:web:249d7a05cba9d1412c8676',
    messagingSenderId: '205307768003',
    projectId: 'hockey-app-f7f17',
    authDomain: 'hockey-app-f7f17.firebaseapp.com',
    storageBucket: 'hockey-app-f7f17.firebasestorage.app',
    measurementId: 'G-MY5JMMHZSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMtk10lJPfZZ879D2IT-RKyLZRR4MSlmc',
    appId: '1:205307768003:android:9c8c4d799f6f9bf12c8676',
    messagingSenderId: '205307768003',
    projectId: 'hockey-app-f7f17',
    storageBucket: 'hockey-app-f7f17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEFtp9Kv3mVGRNhNeUZhEUzD_KRWQwae4',
    appId: '1:205307768003:ios:8a41ff1f5214f25c2c8676',
    messagingSenderId: '205307768003',
    projectId: 'hockey-app-f7f17',
    storageBucket: 'hockey-app-f7f17.firebasestorage.app',
    iosBundleId: 'com.example.hockeyUnionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEFtp9Kv3mVGRNhNeUZhEUzD_KRWQwae4',
    appId: '1:205307768003:ios:8a41ff1f5214f25c2c8676',
    messagingSenderId: '205307768003',
    projectId: 'hockey-app-f7f17',
    storageBucket: 'hockey-app-f7f17.firebasestorage.app',
    iosBundleId: 'com.example.hockeyUnionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlDV8cFGhp1NPohbdDY-ZgC4OxPwQ6rVQ',
    appId: '1:205307768003:web:aaaf2305a12cf28e2c8676',
    messagingSenderId: '205307768003',
    projectId: 'hockey-app-f7f17',
    authDomain: 'hockey-app-f7f17.firebaseapp.com',
    storageBucket: 'hockey-app-f7f17.firebasestorage.app',
    measurementId: 'G-EWC7RVQHBZ',
  );
}
